Class {
	#name : #WDCEGameFrameworkExampleGameEditorSettings,
	#superclass : #WDEWodenGameFrameworkSettings,
	#category : #'WodenCoreExamples-GameFramework-Editor'
}

{ #category : #accessing }
WDCEGameFrameworkExampleGameEditorSettings >> applicationSettings [
	^	WDCEGameFrameworkApplicationSettings

]

{ #category : #accessing }
WDCEGameFrameworkExampleGameEditorSettings >> name [
	^ 'Woden Core Examples - Game Framework'
]
